### ISSUE TITLE
Issues with design_effect and models fit with lmerTest

### ISSUE THREAD

**Issue by acircleda** [lrocconi/mlmhelpr#18]
`design_effect` does not work with models fit with lmerTest package

**Comment by lrocconi** [comment]
to my knowledge, none of the functions have been tested using the lmerTest package only the lme4 package

**Comment by acircleda** [comment]
no problem; I just noticed it was the only function not working when I was using `mlmhelpr` on my dissertation data. I'll see if I can get it working next time I work on the package
